services:
  - type: web
    name: movieott
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://movieott.onrender.com
